include:
  - project: dcvm5/ci-templates
    ref: develop
    file: /AutoDeploy.gitlab-ci.yml

variables:
  SONAR_JAVA_BINARIES_PATH: "src/main/java/com/x5/bigdata/dvcm/process"
  BUILD: "TRUE"
  BUILD_IMAGE: "TRUE"
  LINTER: "FALSE"
  DEPLOY: "TRUE"

deploy:dev:
  variables:
    KUBE_CONFIG: "${KUBE_CONFIG_DEV}"
    STAND: dev
  extends: .deploy